[app]
overall = { bg = "{{ background }}" }

[mgr]
cwd = { fg = "{{ cyan }}" }

find_keyword  = { fg = "{{ yellow }}", italic = true }
find_position = { fg = "{{ magenta }}", bg = "reset", italic = true }

marker_copied   = { fg = "{{ green }}", bg = "{{ green }}" }
marker_cut      = { fg = "{{ red }}", bg = "{{ red }}" }
marker_marked   = { fg = "{{ cyan }}", bg = "{{ cyan }}" }
marker_selected = { fg = "{{ accent }}", bg = "{{ accent }}" }

count_copied   = { fg = "{{ background }}", bg = "{{ green }}" }
count_cut      = { fg = "{{ background }}", bg = "{{ red }}" }
count_selected = { fg = "{{ background }}", bg = "{{ accent }}" }

border_symbol = "│"
border_style  = { fg = "{{ muted }}" }


[tabs]
active   = { fg = "{{ background }}", bg = "{{ foreground }}", bold = true }
inactive = { fg = "{{ foreground }}", bg = "{{ selection }}" }

[mode]
normal_main = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
normal_alt  = { fg = "{{ accent }}", bg = "{{ selection }}"}

select_main = { fg = "{{ background }}", bg = "{{ green }}", bold = true }
select_alt  = { fg = "{{ green }}", bg = "{{ selection }}"}

unset_main  = { fg = "{{ background }}", bg = "{{ red }}", bold = true }
unset_alt   = { fg = "{{ red }}", bg = "{{ selection }}"}

[indicator]
parent = { fg = "{{ background }}", bg = "{{ foreground }}" }
current = { fg = "{{ background }}", bg = "{{ accent }}" }
preview = { fg = "{{ background }}", bg = "{{ foreground }}" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "{{ green }}", bg = "{{ selection }}" }
progress_error  = { fg = "{{ yellow }}", bg = "{{ red }}" }

perm_type  = { fg = "{{ accent }}" }
perm_read  = { fg = "{{ yellow }}" }
perm_write = { fg = "{{ red }}" }
perm_exec  = { fg = "{{ green }}" }
perm_sep   = { fg = "{{ muted }}" }

[input]
border   = { fg = "{{ accent }}" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "{{ accent }}" }
active   = { fg = "{{ magenta }}" }
inactive = {}

[confirm]
border     = { fg = "{{ accent }}" }
title      = { fg = "{{ accent }}" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "{{ accent }}" }

[tasks]
border  = { fg = "{{ accent }}" }
title   = {}
hovered = { fg = "{{ magenta }}", bold = true }

[which]
mask            = { bg = "{{ selection }}" }
cand            = { fg = "{{ cyan }}" }
rest            = { fg = "{{ muted }}" }
desc            = { fg = "{{ magenta }}" }
separator       = "  "
separator_style = { fg = "{{ muted }}" }

[help]
on      = { fg = "{{ cyan }}" }
run     = { fg = "{{ magenta }}" }
desc    = { fg = "{{ muted }}" }
hovered = { bg = "{{ muted }}", bold = true }
footer  = { fg = "{{ foreground }}", bg = "{{ selection }}" }

[notify]
title_info  = { fg = "{{ cyan }}" }
title_warn  = { fg = "{{ yellow }}" }
title_error = { fg = "{{ red }}" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "{{ yellow }}" },
	{ mime = "{audio,video}/*", fg = "{{ magenta }}" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{ red }}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "{{ accent }}" },

	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "{{ selection }}" },

	# Special file
	{ url = "*", is = "orphan", bg = "{{ red }}" },
	{ url = "*", is = "exec"  , fg = "{{ green }}" },

	# Dummy file
	{ url = "*", is = "dummy", bg = "{{ red }}" },
	{ url = "*/", is = "dummy", bg = "{{ red }}" },

	# Fallback
	{ url = "*/", fg = "{{ accent }}" },
]

[spot]
border = { fg = "{{ accent }}" }
title  = { fg = "{{ accent }}" }
tbl_cell = { fg = "{{ accent }}", reversed = true }
tbl_col = { bold = true }

[icon]
dirs = [
	{ name = ".config", text = "", fg = "{{ accent }}" },
	{ name = ".git", text = "", fg = "{{ accent }}" },
	{ name = ".github", text = "", fg = "{{ accent }}" },
	{ name = ".npm", text = "", fg = "{{ accent }}" },
	{ name = "Desktop", text = "", fg = "{{ accent }}" },
	{ name = "Development", text = "", fg = "{{ accent }}" },
	{ name = "Documents", text = "", fg = "{{ accent }}" },
	{ name = "Downloads", text = "", fg = "{{ accent }}" },
	{ name = "Library", text = "", fg = "{{ accent }}" },
	{ name = "Movies", text = "", fg = "{{ accent }}" },
	{ name = "Music", text = "", fg = "{{ accent }}" },
	{ name = "Pictures", text = "", fg = "{{ accent }}" },
	{ name = "Public", text = "", fg = "{{ accent }}" },
	{ name = "Videos", text = "", fg = "{{ accent }}" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "{{ foreground }}" },
	{ if = "link", text = "", fg = "#6c6f85" },
	{ if = "block", text = "", fg = "{{ yellow }}" },
	{ if = "char", text = "", fg = "{{ yellow }}" },
	{ if = "fifo", text = "", fg = "{{ yellow }}" },
	{ if = "sock", text = "", fg = "{{ yellow }}" },
	{ if = "sticky", text = "", fg = "{{ yellow }}" },
	{ if = "dummy", text = "", fg = "{{ red }}" },

	# Fallback
	{ if = "dir", text = "", fg = "{{ accent }}" },
	{ if = "exec", text = "", fg = "{{ green }}" },
	{ if = "!dir", text = "", fg = "{{ foreground }}" },
]

files = [
	{ name = "eslint.config.cjs", text = "", fg = "#8839ef" },
	{ name = "hyprlandd.conf", text = "", fg = "#209fb5" },
	{ name = "settings.gradle", text = "", fg = "{{ accent }}" },
	{ name = "PrusaSlicerGcodeViewer.ini", text = "", fg = "#fe640b" },
	{ name = ".nvmrc", text = "", fg = "{{ green }}" },
	{ name = ".gitmodules", text = "", fg = "#fe640b" },
	{ name = "tailwind.config.ts", text = "󱏿", fg = "#209fb5" },
	{ name = "bun.lockb", text = "", fg = "{{ background }}" },
	{ name = ".npmignore", text = "", fg = "#e64553" },
	{ name = "wrangler.jsonc", text = "", fg = "#fe640b" },
	{ name = ".prettierrc.toml", text = "", fg = "#7287fd" },
	{ name = ".zshenv", text = "", fg = "{{ green }}" },
	{ name = "code_of_conduct", text = "", fg = "#e64553" },
	{ name = ".Xauthority", text = "", fg = "#fe640b" },
	{ name = "gradle-wrapper.properties", text = "", fg = "{{ accent }}" },
	{ name = ".clang-tidy", text = "", fg = "#7c7f93" },
	{ name = ".prettierrc.cjs", text = "", fg = "#7287fd" },
	{ name = ".clangd", text = "", fg = "#7c7f93" },
	{ name = "playwright.config.js", text = "", fg = "{{ green }}" },
	{ name = ".Xresources", text = "", fg = "#fe640b" },
	{ name = "weston.ini", text = "", fg = "{{ yellow }}" },
	{ name = "vite.config.mts", text = "", fg = "{{ yellow }}" },
	{ name = "vercel.json", text = "", fg = "{{ background }}" },
	{ name = "docker-compose.yaml", text = "󰡨", fg = "#7287fd" },
	{ name = "compose.yaml", text = "󰡨", fg = "#7287fd" },
	{ name = "build", text = "", fg = "{{ green }}" },
	{ name = ".luaurc", text = "", fg = "#04a5e5" },
	{ name = "AUTHORS.txt", text = "", fg = "#7287fd" },
	{ name = "pnpm-lock.yaml", text = "", fg = "{{ yellow }}" },
	{ name = ".codespellrc", text = "󰓆", fg = "{{ green }}" },
	{ name = "mix.lock", text = "", fg = "#7c7f93" },
	{ name = "hyprlock.conf", text = "", fg = "#209fb5" },
	{ name = "bspwmrc", text = "", fg = "{{ foreground }}" },
	{ name = ".prettierrc.json5", text = "", fg = "#7287fd" },
	{ name = "license.md", text = "", fg = "{{ yellow }}" },
	{ name = ".prettierignore", text = "", fg = "#7287fd" },
	{ name = "fp-info-cache", text = "", fg = "{{ background }}" },
	{ name = "kdeglobals", text = "", fg = "#04a5e5" },
	{ name = ".zshrc", text = "", fg = "{{ green }}" },
	{ name = "webpack", text = "󰜫", fg = "#209fb5" },
	{ name = "checkhealth", text = "󰓙", fg = "#04a5e5" },
	{ name = ".npmrc", text = "", fg = "#e64553" },
	{ name = "PKGBUILD", text = "", fg = "#04a5e5" },
	{ name = ".prettierrc.yml", text = "", fg = "#7287fd" },
	{ name = "commit_editmsg", text = "", fg = "#fe640b" },
	{ name = ".gitattributes", text = "", fg = "#fe640b" },
	{ name = ".vimrc", text = "", fg = "{{ green }}" },
	{ name = "xsettingsd.conf", text = "", fg = "#fe640b" },
	{ name = "gruntfile.babel.js", text = "", fg = "#fe640b" },
	{ name = "xorg.conf", text = "", fg = "#fe640b" },
	{ name = "xmonad.hs", text = "", fg = "#e64553" },
	{ name = "xmobarrc.hs", text = "", fg = "#e64553" },
	{ name = "rakefile", text = "", fg = "{{ red }}" },
	{ name = "vite.config.mjs", text = "", fg = "{{ yellow }}" },
	{ name = "xdph.conf", text = "", fg = "#209fb5" },
	{ name = "wrangler.toml", text = "", fg = "#fe640b" },
	{ name = ".babelrc", text = "", fg = "{{ green }}" },
	{ name = "AUTHORS", text = "", fg = "#7287fd" },
	{ name = "lxde-rc.xml", text = "", fg = "#8c8fa1" },
	{ name = "vlcrc", text = "󰕼", fg = "#fe640b" },
	{ name = "vitest.config.ts", text = "", fg = "{{ green }}" },
	{ name = "prisma.config.mts", text = "", fg = "{{ accent }}" },
	{ name = "vitest.config.mts", text = "", fg = "{{ green }}" },
	{ name = ".env", text = "", fg = "{{ yellow }}" },
	{ name = "vitest.config.mjs", text = "", fg = "{{ green }}" },
	{ name = ".condarc", text = "", fg = "{{ green }}" },
	{ name = ".pre-commit-config.yaml", text = "󰛢", fg = "{{ yellow }}" },
	{ name = "_vimrc", text = "", fg = "{{ green }}" },
	{ name = "vitest.config.cts", text = "", fg = "{{ green }}" },
	{ name = "vitest.config.cjs", text = "", fg = "{{ green }}" },
	{ name = "PrusaSlicer.ini", text = "", fg = "#fe640b" },
	{ name = "vite.config.ts", text = "", fg = "{{ yellow }}" },
	{ name = "xmobarrc", text = "", fg = "#e64553" },
	{ name = ".editorconfig", text = "", fg = "{{ background }}" },
	{ name = ".xinitrc", text = "", fg = "#fe640b" },
	{ name = "vite.config.cts", text = "", fg = "{{ yellow }}" },
	{ name = "prettier.config.mjs", text = "", fg = "#7287fd" },
	{ name = "vite.config.cjs", text = "", fg = "{{ yellow }}" },
	{ name = "ext_typoscript_setup.txt", text = "", fg = "{{ yellow }}" },
	{ name = ".prettierrc", text = "", fg = "#7287fd" },
	{ name = "hypridle.conf", text = "", fg = "#209fb5" },
	{ name = "containerfile", text = "󰡨", fg = "#7287fd" },
	{ name = "vagrantfile", text = "", fg = "{{ accent }}" },
	{ name = ".gitlab-ci.yml", text = "", fg = "#e64553" },
	{ name = ".gtkrc-2.0", text = "", fg = "{{ background }}" },
	{ name = "unlicense", text = "", fg = "{{ yellow }}" },
	{ name = "tsconfig.json", text = "", fg = "#209fb5" },
	{ name = "tmux.conf.local", text = "", fg = "{{ green }}" },
	{ name = "justfile", text = "", fg = "#7c7f93" },
	{ name = "readme.md", text = "󰂺", fg = "{{ background }}" },
	{ name = "tailwind.config.js", text = "󱏿", fg = "#209fb5" },
	{ name = "license", text = "", fg = "{{ yellow }}" },
	{ name = "sym-lib-table", text = "", fg = "{{ background }}" },
	{ name = "sxhkdrc", text = "", fg = "{{ foreground }}" },
	{ name = ".gvimrc", text = "", fg = "{{ green }}" },
	{ name = ".SRCINFO", text = "󰣇", fg = "#04a5e5" },
	{ name = "svelte.config.js", text = "", fg = "#fe640b" },
	{ name = "security.md", text = "󰒃", fg = "#bcc0cc" },
	{ name = "Directory.Build.targets", text = "", fg = "#04a5e5" },
	{ name = "i3status.conf", text = "", fg = "#e6e9ef" },
	{ name = "cmakelists.txt", text = "", fg = "#dce0e8" },
	{ name = "robots.txt", text = "󰚩", fg = "#6c6f85" },
	{ name = "gulpfile.ts", text = "", fg = "{{ red }}" },
	{ name = ".dockerignore", text = "󰡨", fg = "#7287fd" },
	{ name = "rmd", text = "", fg = "#209fb5" },
	{ name = "nuxt.config.ts", text = "󱄆", fg = "{{ green }}" },
	{ name = "gruntfile.js", text = "", fg = "#fe640b" },
	{ name = "prisma.config.ts", text = "", fg = "{{ accent }}" },
	{ name = "cantorrc", text = "", fg = "#04a5e5" },
	{ name = "tailwind.config.mjs", text = "󱏿", fg = "#209fb5" },
	{ name = "hyprsunset.conf", text = "", fg = "#209fb5" },
	{ name = "readme", text = "󰂺", fg = "{{ background }}" },
	{ name = "py.typed", text = "", fg = "{{ yellow }}" },
	{ name = "procfile", text = "", fg = "#7c7f93" },
	{ name = "eslint.config.ts", text = "", fg = "#8839ef" },
	{ name = "ionic.config.json", text = "", fg = "#7287fd" },
	{ name = "prettier.config.ts", text = "", fg = "#7287fd" },
	{ name = "index.theme", text = "", fg = "{{ green }}" },
	{ name = "prettier.config.cjs", text = "", fg = "#7287fd" },
	{ name = "pom.xml", text = "", fg = "{{ red }}" },
	{ name = "gruntfile.ts", text = "", fg = "#fe640b" },
	{ name = "package-lock.json", text = "", fg = "{{ red }}" },
	{ name = "gtkrc", text = "", fg = "{{ background }}" },
	{ name = ".xsession", text = "", fg = "#fe640b" },
	{ name = "Directory.Packages.props", text = "", fg = "#04a5e5" },
	{ name = "brewfile", text = "", fg = "{{ red }}" },
	{ name = "playwright.config.mts", text = "", fg = "{{ green }}" },
	{ name = "bun.lock", text = "", fg = "{{ background }}" },
	{ name = ".justfile", text = "", fg = "#7c7f93" },
	{ name = "playwright.config.mjs", text = "", fg = "{{ green }}" },
	{ name = ".prettierrc.js", text = "", fg = "#7287fd" },
	{ name = ".gitconfig", text = "", fg = "#fe640b" },
	{ name = "kalgebrarc", text = "", fg = "#04a5e5" },
	{ name = "nuxt.config.mjs", text = "󱄆", fg = "{{ green }}" },
	{ name = "platformio.ini", text = "", fg = "#fe640b" },
	{ name = ".bash_profile", text = "", fg = "{{ green }}" },
	{ name = "build.gradle", text = "", fg = "{{ accent }}" },
	{ name = "package.json", text = "", fg = "#e64553" },
	{ name = "playwright.config.ts", text = "", fg = "{{ green }}" },
	{ name = "next.config.js", text = "", fg = "{{ background }}" },
	{ name = "nuxt.config.js", text = "󱄆", fg = "{{ green }}" },
	{ name = ".git-blame-ignore-revs", text = "", fg = "#fe640b" },
	{ name = "node_modules", text = "", fg = "#e64553" },
	{ name = "next.config.ts", text = "", fg = "{{ background }}" },
	{ name = "go.mod", text = "", fg = "#04a5e5" },
	{ name = ".settings.json", text = "", fg = "#8839ef" },
	{ name = "favicon.ico", text = "", fg = "{{ green }}" },
	{ name = "kdenliverc", text = "", fg = "#04a5e5" },
	{ name = "makefile", text = "", fg = "#7c7f93" },
	{ name = "prettier.config.js", text = "", fg = "#7287fd" },
	{ name = "kritarc", text = "", fg = "{{ magenta }}" },
	{ name = "kritadisplayrc", text = "", fg = "{{ magenta }}" },
	{ name = "mpv.conf", text = "", fg = "{{ foreground }}" },
	{ name = "kdenlive-layoutsrc", text = "", fg = "#04a5e5" },
	{ name = "playwright.config.cjs", text = "", fg = "{{ green }}" },
	{ name = "tmux.conf", text = "", fg = "{{ green }}" },
	{ name = ".zprofile", text = "", fg = "{{ green }}" },
	{ name = "lxqt.conf", text = "", fg = "#04a5e5" },
	{ name = ".mailmap", text = "󰊢", fg = "#fe640b" },
	{ name = "security", text = "󰒃", fg = "#bcc0cc" },
	{ name = "go.sum", text = "", fg = "#04a5e5" },
	{ name = ".prettierrc.json", text = "", fg = "#7287fd" },
	{ name = "config", text = "", fg = "#7c7f93" },
	{ name = "FreeCAD.conf", text = "", fg = "{{ red }}" },
	{ name = "i3blocks.conf", text = "", fg = "#e6e9ef" },
	{ name = "commitlint.config.js", text = "󰜘", fg = "{{ cyan }}" },
	{ name = "i18n.config.js", text = "󰗊", fg = "#7287fd" },
	{ name = ".pnpmfile.cjs", text = "", fg = "{{ yellow }}" },
	{ name = ".luacheckrc", text = "", fg = "#04a5e5" },
	{ name = "vitest.config.js", text = "", fg = "{{ green }}" },
	{ name = "code_of_conduct.md", text = "", fg = "#e64553" },
	{ name = "hyprland.conf", text = "", fg = "#209fb5" },
	{ name = "dune", text = "", fg = "{{ red }}" },
	{ name = "_gvimrc", text = "", fg = "{{ green }}" },
	{ name = "Directory.Build.props", text = "", fg = "#04a5e5" },
	{ name = "gradlew", text = "", fg = "{{ accent }}" },
	{ name = "gulpfile.coffee", text = "", fg = "{{ red }}" },
	{ name = "gulpfile.babel.js", text = "", fg = "{{ red }}" },
	{ name = "pnpm-workspace.yaml", text = "", fg = "{{ yellow }}" },
	{ name = "eslint.config.js", text = "", fg = "#8839ef" },
	{ name = "dockerfile", text = "󰡨", fg = "#7287fd" },
	{ name = "groovy", text = "", fg = "{{ light_foreground }}" },
	{ name = ".gitignore", text = "", fg = "#fe640b" },
	{ name = ".bashrc", text = "", fg = "{{ green }}" },
	{ name = "gulpfile.js", text = "", fg = "{{ red }}" },
	{ name = "gruntfile.coffee", text = "", fg = "#fe640b" },
	{ name = "go.work", text = "", fg = "#04a5e5" },
	{ name = "next.config.cjs", text = "", fg = "{{ background }}" },
	{ name = ".eslintrc", text = "", fg = "#8839ef" },
	{ name = "commitlint.config.ts", text = "󰜘", fg = "{{ cyan }}" },
	{ name = "compose.yml", text = "󰡨", fg = "#7287fd" },
	{ name = "eslint.config.mjs", text = "", fg = "#8839ef" },
	{ name = "gradle.properties", text = "", fg = "{{ accent }}" },
	{ name = ".clang-format", text = "", fg = "#7c7f93" },
	{ name = "docker-compose.yml", text = "󰡨", fg = "#7287fd" },
	{ name = "copying.lesser", text = "", fg = "{{ green }}" },
	{ name = "copying", text = "", fg = "{{ green }}" },
	{ name = "fp-lib-table", text = "", fg = "{{ background }}" },
	{ name = ".nuxtrc", text = "󱄆", fg = "{{ green }}" },
	{ name = "gnumakefile", text = "", fg = "#7c7f93" },
	{ name = "i18n.config.ts", text = "󰗊", fg = "#7287fd" },
	{ name = ".pylintrc", text = "", fg = "#7c7f93" },
	{ name = "build.zig.zon", text = "", fg = "{{ yellow }}" },
	{ name = ".prettierrc.mjs", text = "", fg = "#7287fd" },
	{ name = "hyprpaper.conf", text = "", fg = "#209fb5" },
	{ name = "QtProject.conf", text = "", fg = "{{ green }}" },
	{ name = ".ds_store", text = "", fg = "{{ foreground }}" },
	{ name = "Jenkinsfile", text = "", fg = "{{ red }}" },
	{ name = "Gemfile", text = "", fg = "{{ red }}" },
	{ name = "workspace", text = "", fg = "{{ green }}" },
	{ name = "vite.config.js", text = "", fg = "{{ yellow }}" },
	{ name = ".nanorc", text = "", fg = "{{ foreground }}" },
	{ name = ".prettierrc.yaml", text = "", fg = "#7287fd" },
	{ name = "bitbucket-pipelines.yml", text = "󰂨", fg = "#7287fd" },
	{ name = "playwright.config.cts", text = "", fg = "{{ green }}" },
	{ name = "nuxt.config.cjs", text = "󱄆", fg = "{{ green }}" },
	{ name = ".eslintignore", text = "", fg = "#8839ef" },
]
exts = [
	{ name = "txt", text = "󰈙", fg = "{{ green }}" },
	{ name = "kicad_dru", text = "", fg = "{{ background }}" },
	{ name = "cbl", text = "", fg = "{{ accent }}" },
	{ name = "mpp", text = "", fg = "#209fb5" },
	{ name = "cljc", text = "", fg = "{{ green }}" },
	{ name = "jsonl", text = "", fg = "{{ green }}" },
	{ name = "exs", text = "", fg = "#7c7f93" },
	{ name = "liquid", text = "", fg = "{{ green }}" },
	{ name = "vue", text = "", fg = "{{ green }}" },
	{ name = "hrl", text = "", fg = "{{ magenta }}" },
	{ name = "app", text = "", fg = "{{ red }}" },
	{ name = "stories.vue", text = "", fg = "#e64553" },
	{ name = "avi", text = "", fg = "{{ yellow }}" },
	{ name = "makefile", text = "", fg = "#7c7f93" },
	{ name = "hpp", text = "", fg = "#7c7f93" },
	{ name = "ino", text = "", fg = "#209fb5" },
	{ name = "drl", text = "", fg = "#dc8a78" },
	{ name = "epp", text = "", fg = "{{ yellow }}" },
	{ name = "gv", text = "󱁉", fg = "{{ accent }}" },
	{ name = "cpp", text = "", fg = "#209fb5" },
	{ name = "stories.jsx", text = "", fg = "#e64553" },
	{ name = "git", text = "", fg = "#fe640b" },
	{ name = "tgz", text = "", fg = "{{ yellow }}" },
	{ name = "ical", text = "", fg = "{{ foreground }}" },
	{ name = "R", text = "󰟔", fg = "{{ accent }}" },
	{ name = "ogv", text = "", fg = "{{ yellow }}" },
	{ name = "strings", text = "", fg = "#209fb5" },
	{ name = "bmp", text = "", fg = "#7c7f93" },
	{ name = "styl", text = "", fg = "{{ green }}" },
	{ name = "ex", text = "", fg = "#7c7f93" },
	{ name = "d", text = "", fg = "{{ red }}" },
	{ name = "c", text = "", fg = "#7287fd" },
	{ name = "huff", text = "󰡘", fg = "#8839ef" },
	{ name = "pyw", text = "", fg = "#04a5e5" },
	{ name = "a", text = "", fg = "#e6e9ef" },
	{ name = "bicep", text = "", fg = "#209fb5" },
	{ name = "download", text = "", fg = "{{ green }}" },
	{ name = "pyo", text = "", fg = "{{ yellow }}" },
	{ name = "cu", text = "", fg = "{{ green }}" },
	{ name = "h", text = "", fg = "#7c7f93" },
	{ name = "blend", text = "󰂫", fg = "#fe640b" },
	{ name = "zip", text = "", fg = "{{ yellow }}" },
	{ name = "unity", text = "", fg = "{{ background }}" },
	{ name = "zig", text = "", fg = "{{ yellow }}" },
	{ name = "yml", text = "", fg = "{{ red }}" },
	{ name = "m", text = "", fg = "#7287fd" },
	{ name = "xz", text = "", fg = "{{ yellow }}" },
	{ name = "ifc", text = "󰻫", fg = "{{ green }}" },
	{ name = "xul", text = "", fg = "#fe640b" },
	{ name = "ebuild", text = "", fg = "{{ foreground }}" },
	{ name = "f#", text = "", fg = "#209fb5" },
	{ name = "fish", text = "", fg = "{{ light_foreground }}" },
	{ name = "scm", text = "󰘧", fg = "{{ background }}" },
	{ name = "tbc", text = "󰛓", fg = "{{ accent }}" },
	{ name = "slim", text = "", fg = "#fe640b" },
	{ name = "pyi", text = "", fg = "{{ yellow }}" },
	{ name = "xpi", text = "", fg = "#fe640b" },
	{ name = "astro", text = "", fg = "#e64553" },
	{ name = "lrc", text = "󰨖", fg = "{{ yellow }}" },
	{ name = "vala", text = "", fg = "#8839ef" },
	{ name = "tmpl", text = "", fg = "{{ yellow }}" },
	{ name = "xm", text = "", fg = "#209fb5" },
	{ name = "f90", text = "󱈚", fg = "{{ light_foreground }}" },
	{ name = "fods", text = "", fg = "{{ green }}" },
	{ name = "elf", text = "", fg = "{{ red }}" },
	{ name = "pcm", text = "", fg = "{{ accent }}" },
	{ name = "kdenlivetitle", text = "", fg = "#04a5e5" },
	{ name = "xcstrings", text = "", fg = "#209fb5" },
	{ name = "ccm", text = "", fg = "#e64553" },
	{ name = "aac", text = "", fg = "#04a5e5" },
	{ name = "kicad_prl", text = "", fg = "{{ background }}" },
	{ name = "xcplayground", text = "", fg = "#fe640b" },
	{ name = "xcf", text = "", fg = "{{ light_foreground }}" },
	{ name = "cfc", text = "", fg = "#209fb5" },
	{ name = "less", text = "", fg = "{{ foreground }}" },
	{ name = "hh", text = "", fg = "#7c7f93" },
	{ name = "xaml", text = "󰙳", fg = "#8839ef" },
	{ name = "hx", text = "", fg = "{{ yellow }}" },
	{ name = "wvc", text = "", fg = "#04a5e5" },
	{ name = "pck", text = "", fg = "#7c7f93" },
	{ name = "eot", text = "", fg = "{{ background }}" },
	{ name = "docx", text = "󰈬", fg = "{{ accent }}" },
	{ name = "sqlite3", text = "", fg = "#dce0e8" },
	{ name = "wv", text = "", fg = "#04a5e5" },
	{ name = "cxxm", text = "", fg = "#209fb5" },
	{ name = "dot", text = "󱁉", fg = "{{ accent }}" },
	{ name = "tsconfig", text = "", fg = "{{ yellow }}" },
	{ name = "wrz", text = "󰆧", fg = "#8c8fa1" },
	{ name = "stl", text = "󰆧", fg = "#8c8fa1" },
	{ name = "wrl", text = "󰆧", fg = "#8c8fa1" },
	{ name = "gz", text = "", fg = "{{ yellow }}" },
	{ name = "woff2", text = "", fg = "{{ background }}" },
	{ name = "stories.mjs", text = "", fg = "#e64553" },
	{ name = "fctb", text = "", fg = "{{ red }}" },
	{ name = "asm", text = "", fg = "#04a5e5" },
	{ name = "ogx", text = "", fg = "{{ yellow }}" },
	{ name = "wmv", text = "", fg = "{{ yellow }}" },
	{ name = "terminal", text = "", fg = "{{ green }}" },
	{ name = "webpack", text = "󰜫", fg = "#209fb5" },
	{ name = "v", text = "󰍛", fg = "{{ green }}" },
	{ name = "webmanifest", text = "", fg = "{{ yellow }}" },
	{ name = "webm", text = "", fg = "{{ yellow }}" },
	{ name = "wav", text = "", fg = "#04a5e5" },
	{ name = "wasm", text = "", fg = "#8839ef" },
	{ name = "ape", text = "", fg = "#04a5e5" },
	{ name = "pot", text = "", fg = "#209fb5" },
	{ name = "skp", text = "󰻫", fg = "{{ green }}" },
	{ name = "license", text = "", fg = "{{ green }}" },
	{ name = "vsix", text = "", fg = "#8839ef" },
	{ name = "vsh", text = "", fg = "#7287fd" },
	{ name = "vim", text = "", fg = "{{ green }}" },
	{ name = "ai", text = "", fg = "{{ green }}" },
	{ name = "fctl", text = "", fg = "{{ red }}" },
	{ name = "markdown", text = "", fg = "#e6e9ef" },
	{ name = "cts", text = "", fg = "#209fb5" },
	{ name = "config.ru", text = "", fg = "{{ red }}" },
	{ name = "stp", text = "󰻫", fg = "{{ green }}" },
	{ name = "feature", text = "", fg = "{{ green }}" },
	{ name = "cfg", text = "", fg = "#7c7f93" },
	{ name = "mov", text = "", fg = "{{ yellow }}" },
	{ name = "ads", text = "", fg = "#7c7f93" },
	{ name = "vh", text = "󰍛", fg = "{{ green }}" },
	{ name = "blp", text = "󰺾", fg = "#7287fd" },
	{ name = "bz", text = "", fg = "{{ yellow }}" },
	{ name = "lff", text = "", fg = "{{ background }}" },
	{ name = "torrent", text = "", fg = "{{ green }}" },
	{ name = "rmd", text = "", fg = "#209fb5" },
	{ name = "mkv", text = "", fg = "{{ yellow }}" },
	{ name = "webp", text = "", fg = "#7c7f93" },
	{ name = "bin", text = "", fg = "{{ red }}" },
	{ name = "svg", text = "󰜡", fg = "{{ yellow }}" },
	{ name = "hxx", text = "", fg = "#7c7f93" },
	{ name = "ui", text = "", fg = "{{ accent }}" },
	{ name = "oga", text = "", fg = "{{ accent }}" },
	{ name = "apk", text = "", fg = "{{ green }}" },
	{ name = "🔥", text = "", fg = "#fe640b" },
	{ name = "cxx", text = "", fg = "#209fb5" },
	{ name = "gradle", text = "", fg = "{{ accent }}" },
	{ name = "ods", text = "", fg = "{{ green }}" },
	{ name = "eex", text = "", fg = "#7c7f93" },
	{ name = "typ", text = "", fg = "#209fb5" },
	{ name = "avif", text = "", fg = "#7c7f93" },
	{ name = "out", text = "", fg = "{{ red }}" },
	{ name = "ogg", text = "", fg = "{{ accent }}" },
	{ name = "import", text = "", fg = "{{ background }}" },
	{ name = "bazel", text = "", fg = "{{ green }}" },
	{ name = "dwg", text = "󰻫", fg = "{{ green }}" },
	{ name = "pxi", text = "", fg = "#04a5e5" },
	{ name = "ttf", text = "", fg = "{{ background }}" },
	{ name = "tsx", text = "", fg = "{{ accent }}" },
	{ name = "tscn", text = "", fg = "#7c7f93" },
	{ name = "kdbx", text = "", fg = "{{ green }}" },
	{ name = "heex", text = "", fg = "#7c7f93" },
	{ name = "sldprt", text = "󰻫", fg = "{{ green }}" },
	{ name = "hex", text = "", fg = "{{ accent }}" },
	{ name = "erb", text = "", fg = "{{ red }}" },
	{ name = "vi", text = "", fg = "{{ yellow }}" },
	{ name = "ksh", text = "", fg = "{{ light_foreground }}" },
	{ name = "sqlite", text = "", fg = "#dce0e8" },
	{ name = "toml", text = "", fg = "{{ red }}" },
	{ name = "spec.jsx", text = "", fg = "#209fb5" },
	{ name = "sh", text = "", fg = "{{ light_foreground }}" },
	{ name = "tfvars", text = "", fg = "#8839ef" },
	{ name = "3gp", text = "", fg = "{{ yellow }}" },
	{ name = "tf", text = "", fg = "#8839ef" },
	{ name = "csh", text = "", fg = "{{ light_foreground }}" },
	{ name = "tex", text = "", fg = "{{ green }}" },
	{ name = "android", text = "", fg = "{{ green }}" },
	{ name = "aiff", text = "", fg = "#04a5e5" },
	{ name = "diff", text = "", fg = "{{ foreground }}" },
	{ name = "7z", text = "", fg = "{{ yellow }}" },
	{ name = "norg", text = "", fg = "{{ accent }}" },
	{ name = "test.tsx", text = "", fg = "{{ accent }}" },
	{ name = "apl", text = "", fg = "{{ green }}" },
	{ name = "sldasm", text = "󰻫", fg = "{{ green }}" },
	{ name = "cjs", text = "", fg = "{{ green }}" },
	{ name = "test.ts", text = "", fg = "#209fb5" },
	{ name = "ejs", text = "", fg = "{{ green }}" },
	{ name = "test.jsx", text = "", fg = "#209fb5" },
	{ name = "test.js", text = "", fg = "{{ green }}" },
	{ name = "wma", text = "", fg = "#04a5e5" },
	{ name = "templ", text = "", fg = "{{ yellow }}" },
	{ name = "msf", text = "", fg = "{{ accent }}" },
	{ name = "query", text = "", fg = "{{ green }}" },
	{ name = "tcl", text = "󰛓", fg = "{{ accent }}" },
	{ name = "desktop", text = "", fg = "{{ foreground }}" },
	{ name = "svx", text = "", fg = "#e64553" },
	{ name = "cobol", text = "", fg = "{{ accent }}" },
	{ name = "t", text = "", fg = "#209fb5" },
	{ name = "swift", text = "", fg = "#fe640b" },
	{ name = "svh", text = "󰍛", fg = "{{ green }}" },
	{ name = "m3u8", text = "󰲹", fg = "#dd7878" },
	{ name = "scad", text = "", fg = "{{ yellow }}" },
	{ name = "svelte", text = "", fg = "#fe640b" },
	{ name = "bak", text = "󰁯", fg = "#7c7f93" },
	{ name = "sv", text = "󰍛", fg = "{{ green }}" },
	{ name = "nu", text = "", fg = "{{ green }}" },
	{ name = "java", text = "", fg = "{{ red }}" },
	{ name = "sublime", text = "", fg = "#fe640b" },
	{ name = "sub", text = "󰨖", fg = "{{ yellow }}" },
	{ name = "jar", text = "", fg = "{{ yellow }}" },
	{ name = "mjs", text = "", fg = "{{ yellow }}" },
	{ name = "magnet", text = "", fg = "{{ red }}" },
	{ name = "el", text = "", fg = "#7c7f93" },
	{ name = "jwmrc", text = "", fg = "{{ accent }}" },
	{ name = "cache", text = "", fg = "{{ background }}" },
	{ name = "odf", text = "", fg = "{{ magenta }}" },
	{ name = "pdf", text = "", fg = "{{ red }}" },
	{ name = "fodp", text = "", fg = "{{ yellow }}" },
	{ name = "vhdl", text = "󰍛", fg = "{{ green }}" },
	{ name = "stories.tsx", text = "", fg = "#e64553" },
	{ name = "jsx", text = "", fg = "#209fb5" },
	{ name = "gql", text = "", fg = "{{ magenta }}" },
	{ name = "cs", text = "󰌛", fg = "{{ green }}" },
	{ name = "pyd", text = "", fg = "{{ yellow }}" },
	{ name = "asc", text = "󰦝", fg = "#6c6f85" },
	{ name = "bz3", text = "", fg = "{{ yellow }}" },
	{ name = "woff", text = "", fg = "{{ background }}" },
	{ name = "otf", text = "", fg = "{{ background }}" },
	{ name = "stories.js", text = "", fg = "#e64553" },
	{ name = "pptx", text = "󰈧", fg = "#e64553" },
	{ name = "elm", text = "", fg = "#209fb5" },
	{ name = "glb", text = "", fg = "{{ yellow }}" },
	{ name = "fsx", text = "", fg = "#209fb5" },
	{ name = "py", text = "", fg = "{{ yellow }}" },
	{ name = "ste", text = "󰻫", fg = "{{ green }}" },
	{ name = "sln", text = "", fg = "#8839ef" },
	{ name = "gleam", text = "", fg = "{{ magenta }}" },
	{ name = "fcscript", text = "", fg = "{{ red }}" },
	{ name = "spec.tsx", text = "", fg = "{{ accent }}" },
	{ name = "eln", text = "", fg = "#7c7f93" },
	{ name = "sql", text = "", fg = "#dce0e8" },
	{ name = "rkt", text = "󰘧", fg = "{{ red }}" },
	{ name = "md5", text = "󰕥", fg = "#7c7f93" },
	{ name = "clj", text = "", fg = "{{ green }}" },
	{ name = "sha224", text = "󰕥", fg = "#7c7f93" },
	{ name = "spec.js", text = "", fg = "{{ green }}" },
	{ name = "sha384", text = "󰕥", fg = "#7c7f93" },
	{ name = "sol", text = "", fg = "#209fb5" },
	{ name = "so", text = "", fg = "#e6e9ef" },
	{ name = "sml", text = "󰘧", fg = "#fe640b" },
	{ name = "mdx", text = "", fg = "#209fb5" },
	{ name = "slvs", text = "󰻫", fg = "{{ green }}" },
	{ name = "slnx", text = "", fg = "#8839ef" },
	{ name = "ssa", text = "󰨖", fg = "{{ yellow }}" },
	{ name = "kra", text = "", fg = "{{ magenta }}" },
	{ name = "sig", text = "󰘧", fg = "#fe640b" },
	{ name = "jpeg", text = "", fg = "#7c7f93" },
	{ name = "cshtml", text = "󱦗", fg = "#8839ef" },
	{ name = "fsi", text = "", fg = "#209fb5" },
	{ name = "coffee", text = "", fg = "{{ green }}" },
	{ name = "bzl", text = "", fg = "{{ green }}" },
	{ name = "sha512", text = "󰕥", fg = "#7c7f93" },
	{ name = "flac", text = "", fg = "{{ accent }}" },
	{ name = "sha256", text = "󰕥", fg = "#7c7f93" },
	{ name = "org", text = "", fg = "{{ cyan }}" },
	{ name = "spec.ts", text = "", fg = "#209fb5" },
	{ name = "brep", text = "󰻫", fg = "{{ green }}" },
	{ name = "pub", text = "󰷖", fg = "{{ yellow }}" },
	{ name = "jsonc", text = "", fg = "{{ green }}" },
	{ name = "sha1", text = "󰕥", fg = "#7c7f93" },
	{ name = "tmux", text = "", fg = "{{ green }}" },
	{ name = "vert", text = "", fg = "#209fb5" },
	{ name = "cpy", text = "", fg = "{{ accent }}" },
	{ name = "xml", text = "󰗀", fg = "#fe640b" },
	{ name = "sc", text = "", fg = "{{ red }}" },
	{ name = "cljs", text = "", fg = "#209fb5" },
	{ name = "kicad_sym", text = "", fg = "{{ background }}" },
	{ name = "bat", text = "", fg = "{{ green }}" },
	{ name = "fodg", text = "", fg = "{{ background }}" },
	{ name = "sass", text = "", fg = "#dd7878" },
	{ name = "cuh", text = "", fg = "#7c7f93" },
	{ name = "rasi", text = "", fg = "{{ green }}" },
	{ name = "dll", text = "", fg = "{{ foreground }}" },
	{ name = "ics", text = "", fg = "{{ foreground }}" },
	{ name = "razor", text = "󱦘", fg = "#8839ef" },
	{ name = "gpr", text = "", fg = "#7c7f93" },
	{ name = "kbx", text = "󰯄", fg = "#7c7f93" },
	{ name = "mustache", text = "", fg = "#fe640b" },
	{ name = "resi", text = "", fg = "#dd7878" },
	{ name = "res", text = "", fg = "{{ red }}" },
	{ name = "mp3", text = "", fg = "#04a5e5" },
	{ name = "hurl", text = "", fg = "#e64553" },
	{ name = "gnumakefile", text = "", fg = "#7c7f93" },
	{ name = "rproj", text = "󰗆", fg = "{{ green }}" },
	{ name = "rar", text = "", fg = "{{ yellow }}" },
	{ name = "rake", text = "", fg = "{{ red }}" },
	{ name = "igs", text = "󰻫", fg = "{{ green }}" },
	{ name = "elc", text = "", fg = "#7c7f93" },
	{ name = "dump", text = "", fg = "#dce0e8" },
	{ name = "qrc", text = "", fg = "{{ green }}" },
	{ name = "qml", text = "", fg = "{{ green }}" },
	{ name = "ifb", text = "", fg = "{{ foreground }}" },
	{ name = "qm", text = "", fg = "#209fb5" },
	{ name = "mm", text = "", fg = "#209fb5" },
	{ name = "pyx", text = "", fg = "#04a5e5" },
	{ name = "typoscript", text = "", fg = "{{ yellow }}" },
	{ name = "pm", text = "", fg = "#209fb5" },
	{ name = "pyc", text = "", fg = "{{ yellow }}" },
	{ name = "mo", text = "", fg = "#7287fd" },
	{ name = "zsh", text = "", fg = "{{ green }}" },
	{ name = "frag", text = "", fg = "#209fb5" },
	{ name = "fbx", text = "󰆧", fg = "#8c8fa1" },
	{ name = "stories.svelte", text = "", fg = "#e64553" },
	{ name = "step", text = "󰻫", fg = "{{ green }}" },
	{ name = "go", text = "", fg = "#04a5e5" },
	{ name = "mp4", text = "", fg = "{{ yellow }}" },
	{ name = "bicepparam", text = "", fg = "#7c7f93" },
	{ name = "c++", text = "", fg = "#e64553" },
	{ name = "ada", text = "", fg = "#7287fd" },
	{ name = "twig", text = "", fg = "{{ green }}" },
	{ name = "pxd", text = "", fg = "#04a5e5" },
	{ name = "odt", text = "", fg = "#04a5e5" },
	{ name = "psd1", text = "󰨊", fg = "#7287fd" },
	{ name = "po", text = "", fg = "#209fb5" },
	{ name = "psd", text = "", fg = "#209fb5" },
	{ name = "cob", text = "", fg = "{{ accent }}" },
	{ name = "rb", text = "", fg = "{{ red }}" },
	{ name = "ps1", text = "󰨊", fg = "{{ accent }}" },
	{ name = "fcmat", text = "", fg = "{{ red }}" },
	{ name = "tres", text = "", fg = "#7c7f93" },
	{ name = "prisma", text = "", fg = "{{ accent }}" },
	{ name = "prefab", text = "", fg = "#04a5e5" },
	{ name = "ppt", text = "󰈧", fg = "#e64553" },
	{ name = "applescript", text = "", fg = "#7c7f93" },
	{ name = "pp", text = "", fg = "{{ yellow }}" },
	{ name = "cp", text = "", fg = "#209fb5" },
	{ name = "png", text = "", fg = "#7c7f93" },
	{ name = "ply", text = "󰆧", fg = "#8c8fa1" },
	{ name = "pls", text = "󰲹", fg = "#dd7878" },
	{ name = "pl", text = "", fg = "#209fb5" },
	{ name = "php", text = "", fg = "#7c7f93" },
	{ name = "dxf", text = "󰻫", fg = "{{ green }}" },
	{ name = "patch", text = "", fg = "{{ foreground }}" },
	{ name = "part", text = "", fg = "{{ green }}" },
	{ name = "opus", text = "", fg = "{{ accent }}" },
	{ name = "gcode", text = "󰐫", fg = "{{ accent }}" },
	{ name = "psm1", text = "󰨊", fg = "#7287fd" },
	{ name = "cppm", text = "", fg = "#209fb5" },
	{ name = "m4v", text = "", fg = "{{ yellow }}" },
	{ name = "fcmacro", text = "", fg = "{{ red }}" },
	{ name = "doc", text = "󰈬", fg = "{{ accent }}" },
	{ name = "odg", text = "", fg = "{{ background }}" },
	{ name = "ko", text = "", fg = "#e6e9ef" },
	{ name = "o", text = "", fg = "{{ red }}" },
	{ name = "suo", text = "", fg = "#8839ef" },
	{ name = "fcstd1", text = "", fg = "{{ red }}" },
	{ name = "http", text = "", fg = "#04a5e5" },
	{ name = "nswag", text = "", fg = "{{ green }}" },
	{ name = "nix", text = "", fg = "#04a5e5" },
	{ name = "kdenlive", text = "", fg = "#04a5e5" },
	{ name = "geom", text = "", fg = "#209fb5" },
	{ name = "nim", text = "", fg = "{{ yellow }}" },
	{ name = "env", text = "", fg = "{{ yellow }}" },
	{ name = "nfo", text = "", fg = "{{ background }}" },
	{ name = "mts", text = "", fg = "#209fb5" },
	{ name = "azcli", text = "", fg = "{{ accent }}" },
	{ name = "bash", text = "", fg = "{{ green }}" },
	{ name = "lock", text = "", fg = "#bcc0cc" },
	{ name = "fcstd", text = "", fg = "{{ red }}" },
	{ name = "vhd", text = "󰍛", fg = "{{ green }}" },
	{ name = "mojo", text = "", fg = "#fe640b" },
	{ name = "luau", text = "", fg = "#04a5e5" },
	{ name = "mli", text = "", fg = "#fe640b" },
	{ name = "ml", text = "", fg = "#fe640b" },
	{ name = "bz2", text = "", fg = "{{ yellow }}" },
	{ name = "mk", text = "", fg = "#7c7f93" },
	{ name = "csv", text = "", fg = "{{ green }}" },
	{ name = "mint", text = "󰌪", fg = "{{ green }}" },
	{ name = "crdownload", text = "", fg = "{{ green }}" },
	{ name = "spx", text = "", fg = "{{ accent }}" },
	{ name = "yaml", text = "", fg = "{{ red }}" },
	{ name = "pro", text = "", fg = "{{ yellow }}" },
	{ name = "material", text = "", fg = "{{ magenta }}" },
	{ name = "m3u", text = "󰲹", fg = "#dd7878" },
	{ name = "odp", text = "", fg = "{{ yellow }}" },
	{ name = "Dockerfile", text = "󰡨", fg = "#7287fd" },
	{ name = "fcbak", text = "", fg = "{{ red }}" },
	{ name = "dconf", text = "", fg = "{{ background }}" },
	{ name = "bqn", text = "", fg = "{{ green }}" },
	{ name = "svgz", text = "󰜡", fg = "{{ yellow }}" },
	{ name = "md", text = "", fg = "#e6e9ef" },
	{ name = "aif", text = "", fg = "#04a5e5" },
	{ name = "bib", text = "󱉟", fg = "{{ green }}" },
	{ name = "mobi", text = "", fg = "{{ yellow }}" },
	{ name = "luac", text = "", fg = "#04a5e5" },
	{ name = "ebook", text = "", fg = "{{ yellow }}" },
	{ name = "krz", text = "", fg = "{{ magenta }}" },
	{ name = "conf", text = "", fg = "#7c7f93" },
	{ name = "iges", text = "󰻫", fg = "{{ green }}" },
	{ name = "exe", text = "", fg = "{{ red }}" },
	{ name = "lua", text = "", fg = "#04a5e5" },
	{ name = "scala", text = "", fg = "{{ red }}" },
	{ name = "signature", text = "󰘧", fg = "#fe640b" },
	{ name = "lib", text = "", fg = "{{ foreground }}" },
	{ name = "image", text = "", fg = "#bcc0cc" },
	{ name = "lhs", text = "", fg = "#7c7f93" },
	{ name = "scss", text = "", fg = "#dd7878" },
	{ name = "leex", text = "", fg = "#7c7f93" },
	{ name = "lck", text = "", fg = "#bcc0cc" },
	{ name = "kicad_sch", text = "", fg = "{{ background }}" },
	{ name = "iso", text = "", fg = "#bcc0cc" },
	{ name = "kts", text = "", fg = "#8839ef" },
	{ name = "kt", text = "", fg = "#8839ef" },
	{ name = "log", text = "󰌱", fg = "#e6e9ef" },
	{ name = "kpp", text = "", fg = "{{ magenta }}" },
	{ name = "obj", text = "󰆧", fg = "#8c8fa1" },
	{ name = "db", text = "", fg = "#dce0e8" },
	{ name = "kicad_wks", text = "", fg = "{{ background }}" },
	{ name = "kicad_pro", text = "", fg = "{{ background }}" },
	{ name = "cow", text = "󰆚", fg = "#fe640b" },
	{ name = "dart", text = "", fg = "{{ accent }}" },
	{ name = "json", text = "", fg = "{{ green }}" },
	{ name = "ico", text = "", fg = "{{ green }}" },
	{ name = "kicad_mod", text = "", fg = "{{ background }}" },
	{ name = "kdb", text = "", fg = "{{ green }}" },
	{ name = "rlib", text = "", fg = "#dc8a78" },
	{ name = "jxl", text = "", fg = "#7c7f93" },
	{ name = "fcparam", text = "", fg = "{{ red }}" },
	{ name = "kicad_pcb", text = "", fg = "{{ background }}" },
	{ name = "haml", text = "", fg = "{{ background }}" },
	{ name = "js", text = "", fg = "{{ green }}" },
	{ name = "jpg", text = "", fg = "#7c7f93" },
	{ name = "jl", text = "", fg = "{{ magenta }}" },
	{ name = "ixx", text = "", fg = "#209fb5" },
	{ name = "ipynb", text = "", fg = "#fe640b" },
	{ name = "cfm", text = "", fg = "#209fb5" },
	{ name = "3mf", text = "󰆧", fg = "#8c8fa1" },
	{ name = "s", text = "", fg = "{{ accent }}" },
	{ name = "hs", text = "", fg = "#7c7f93" },
	{ name = "fodt", text = "", fg = "#04a5e5" },
	{ name = "odin", text = "󰟢", fg = "{{ accent }}" },
	{ name = "cc", text = "", fg = "#e64553" },
	{ name = "r", text = "󰟔", fg = "{{ accent }}" },
	{ name = "srt", text = "󰨖", fg = "{{ yellow }}" },
	{ name = "rs", text = "", fg = "#dc8a78" },
	{ name = "html", text = "", fg = "#fe640b" },
	{ name = "icalendar", text = "", fg = "{{ foreground }}" },
	{ name = "cson", text = "", fg = "{{ green }}" },
	{ name = "x", text = "", fg = "#7287fd" },
	{ name = "xslt", text = "󰗀", fg = "#04a5e5" },
	{ name = "ts", text = "", fg = "#209fb5" },
	{ name = "cast", text = "", fg = "{{ yellow }}" },
	{ name = "csproj", text = "󰪮", fg = "#8839ef" },
	{ name = "hbs", text = "", fg = "#fe640b" },
	{ name = "gemspec", text = "", fg = "{{ red }}" },
	{ name = "sbt", text = "", fg = "{{ red }}" },
	{ name = "cr", text = "", fg = "{{ selection }}" },
	{ name = "psb", text = "", fg = "#209fb5" },
	{ name = "erl", text = "", fg = "{{ magenta }}" },
	{ name = "ige", text = "󰻫", fg = "{{ green }}" },
	{ name = "gif", text = "", fg = "#7c7f93" },
	{ name = "gresource", text = "", fg = "{{ background }}" },
	{ name = "f3d", text = "󰻫", fg = "{{ green }}" },
	{ name = "fsscript", text = "", fg = "#209fb5" },
	{ name = "cljd", text = "", fg = "#209fb5" },
	{ name = "dropbox", text = "", fg = "{{ accent }}" },
	{ name = "txz", text = "", fg = "{{ yellow }}" },
	{ name = "info", text = "", fg = "{{ background }}" },
	{ name = "fnl", text = "", fg = "{{ background }}" },
	{ name = "d.ts", text = "", fg = "{{ yellow }}" },
	{ name = "awk", text = "", fg = "{{ light_foreground }}" },
	{ name = "flc", text = "", fg = "{{ background }}" },
	{ name = "fdmdownload", text = "", fg = "{{ green }}" },
	{ name = "json5", text = "", fg = "{{ green }}" },
	{ name = "img", text = "", fg = "#bcc0cc" },
	{ name = "xlsx", text = "󰈛", fg = "{{ green }}" },
	{ name = "gd", text = "", fg = "#7c7f93" },
	{ name = "htm", text = "", fg = "#fe640b" },
	{ name = "glsl", text = "", fg = "#209fb5" },
	{ name = "epub", text = "", fg = "{{ yellow }}" },
	{ name = "xls", text = "󰈛", fg = "{{ green }}" },
	{ name = "qss", text = "", fg = "{{ green }}" },
	{ name = "rss", text = "", fg = "{{ yellow }}" },
	{ name = "zst", text = "", fg = "{{ yellow }}" },
	{ name = "dockerignore", text = "󰡨", fg = "#7287fd" },
	{ name = "edn", text = "", fg = "#209fb5" },
	{ name = "m4a", text = "", fg = "#04a5e5" },
	{ name = "adb", text = "", fg = "#7287fd" },
	{ name = "flf", text = "", fg = "{{ background }}" },
	{ name = "ini", text = "", fg = "#7c7f93" },
	{ name = "cue", text = "󰲹", fg = "#dd7878" },
	{ name = "conda", text = "", fg = "{{ green }}" },
	{ name = "css", text = "", fg = "#8839ef" },
	{ name = "blade.php", text = "", fg = "#e64553" },
	{ name = "stories.ts", text = "", fg = "#e64553" },
	{ name = "godot", text = "", fg = "#7c7f93" },
	{ name = "fs", text = "", fg = "#209fb5" },
	{ name = "ass", text = "󰨖", fg = "{{ yellow }}" },
	{ name = "graphql", text = "", fg = "{{ magenta }}" },
	{ name = "cmake", text = "", fg = "#dce0e8" },
]
