[settings]
minimum_release_age = "0h"

[tools]
argocd = "latest"
atuin = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
claude = "latest"
codex = "latest"
curlie = "latest"
gh = "latest"
glow = "3.0.0"
helix = "latest"
helm = "latest"
herdr = "latest"
hunk = "latest"
java = "25"
k9s = "latest"
kubectl = "latest"
krew = "latest"
opencode = "latest"
ruff = "latest"
ty = "latest"
uv = "latest"
vault = "latest"
worktrunk = "latest"
yazi = '26.8.15'
yamlfmt = "latest"
yamllint = "latest"
yq = "latest"

# langs --
lua = "latest"
go = "latest"
node = "26.7.0"
python = "latest"
rust = "latest"


# mictrsoft sqlcmd
"github:microsoft/go-sqlcmd" = "latest"
# https://github.com/mrpbennett/bucky
"go:github.com/mrpbennett/bucky/cmd/bucky" = "v0.1.7"
# https://github.com/joshmedeski/sesh
"go:github.com/joshmedeski/sesh/v2" = "latest"
pi = "latest"
duf = "latest"

[settings.upgrade]
auto_prune = false
